// <auto-generated />
using System;
using GrapheneTrace.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GrapheneTrace.Data.Migrations
{
    [DbContext(typeof(GrapheneTraceContext))]
    partial class GrapheneTraceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GrapheneTrace.Core.Models.Alert", b =>
                {
                    b.Property<int>("AlertID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlertID"));

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AcknowledgedBy")
                        .HasColumnType("int");

                    b.Property<int>("AlertType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FrameID")
                        .HasColumnType("int");

                    b.Property<bool>("IsAcknowledged")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.HasKey("AlertID");

                    b.HasIndex("FrameID");

                    b.HasIndex("PatientID", "CreatedAt");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("GrapheneTrace.Core.Models.ClinicalNote", b =>
                {
                    b.Property<int>("NoteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NoteID"));

                    b.Property<int>("ClinicianID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FrameID")
                        .HasColumnType("int");

                    b.Property<string>("NoteText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NoteType")
                        .HasColumnType("int");

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.HasKey("NoteID");

                    b.HasIndex("ClinicianID");

                    b.HasIndex("FrameID");

                    b.HasIndex("PatientID");

                    b.ToTable("ClinicalNotes");
                });

            modelBuilder.Entity("GrapheneTrace.Core.Models.Clinician", b =>
                {
                    b.Property<int>("ClinicianID")
                        .HasColumnType("int");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LicenseNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Specialization")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ClinicianID");

                    b.ToTable("Clinicians");

                    b.HasData(
                        new
                        {
                            ClinicianID = 2,
                            Department = "Internal Medicine",
                            LicenseNumber = "MC12345",
                            Specialization = "Wound Care Specialist"
                        });
                });

            modelBuilder.Entity("GrapheneTrace.Core.Models.ClinicianPatient", b =>
                {
                    b.Property<int>("ClinicianPatientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClinicianPatientID"));

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ClinicianID")
                        .HasColumnType("int");

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.HasKey("ClinicianPatientID");

                    b.HasIndex("ClinicianID");

                    b.HasIndex("PatientID");

                    b.ToTable("ClinicianPatients");

                    b.HasData(
                        new
                        {
                            ClinicianPatientID = 1,
                            AssignedDate = new DateTime(2025, 12, 4, 13, 57, 53, 234, DateTimeKind.Local).AddTicks(2305),
                            ClinicianID = 2,
                            PatientID = 3
                        });
                });

            modelBuilder.Entity("GrapheneTrace.Core.Models.Comment", b =>
                {
                    b.Property<int>("CommentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentID"));

                    b.Property<int>("AuthorID")
                        .HasColumnType("int");

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FrameID")
                        .HasColumnType("int");

                    b.Property<int?>("ParentCommentID")
                        .HasColumnType("int");

                    b.Property<int?>("PatientID")
                        .HasColumnType("int");

                    b.HasKey("CommentID");

                    b.HasIndex("AuthorID");

                    b.HasIndex("FrameID");

                    b.HasIndex("ParentCommentID");

                    b.HasIndex("PatientID");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("GrapheneTrace.Core.Models.FrameMetric", b =>
                {
                    b.Property<int>("MetricID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MetricID"));

                    b.Property<double>("AveragePressure")
                        .HasColumnType("float");

                    b.Property<double>("ContactAreaPercentage")
                        .HasColumnType("float");

                    b.Property<int>("FrameID")
                        .HasColumnType("int");

                    b.Property<double>("MaxPressureValue")
                        .HasColumnType("float");

                    b.Property<double>("PeakPressureIndex")
                        .HasColumnType("float");

                    b.HasKey("MetricID");

                    b.HasIndex("FrameID")
                        .IsUnique();

                    b.ToTable("FrameMetrics");
                });

            modelBuilder.Entity("GrapheneTrace.Core.Models.Patient", b =>
                {
                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("AdmissionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("MedicalRecordNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RiskLevel")
                        .HasColumnType("int");

                    b.HasKey("PatientID");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            PatientID = 3,
                            AdmissionDate = new DateTime(2025, 12, 4, 13, 57, 53, 234, DateTimeKind.Local).AddTicks(2008),
                            DateOfBirth = new DateTime(1950, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MedicalRecordNumber = "MRN001",
                            RiskLevel = 2
                        });
                });

            modelBuilder.Entity("GrapheneTrace.Core.Models.SensorFrame", b =>
                {
                    b.Property<int>("FrameID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FrameID"));

                    b.Property<string>("FilePath")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FrameData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("FrameID");

                    b.HasIndex("PatientID", "Timestamp");

                    b.ToTable("SensorFrames");
                });

            modelBuilder.Entity("GrapheneTrace.Core.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            CreatedAt = new DateTime(2025, 12, 11, 13, 57, 52, 599, DateTimeKind.Local).AddTicks(6068),
                            Email = "admin@graphenetrace.com",
                            FirstName = "System",
                            IsActive = true,
                            LastName = "Administrator",
                            PasswordHash = "$2a$11$1xf9G3i0ubxlfzXhgITQZ../asOB5e6nIBcS2MdehmGQKy993y/Ie",
                            Role = 0,
                            Username = "admin"
                        },
                        new
                        {
                            UserID = 2,
                            CreatedAt = new DateTime(2025, 12, 11, 13, 57, 52, 916, DateTimeKind.Local).AddTicks(4534),
                            Email = "john.smith@hospital.com",
                            FirstName = "John",
                            IsActive = true,
                            LastName = "Smith",
                            PasswordHash = "$2a$11$ghYPK/WJWwQ8wU569DlCOe4tatBiyDf6yOm4ZnT2LJ.Z2PgjAAa8K",
                            Role = 1,
                            Username = "dr.smith"
                        },
                        new
                        {
                            UserID = 3,
                            CreatedAt = new DateTime(2025, 12, 11, 13, 57, 53, 233, DateTimeKind.Local).AddTicks(9624),
                            Email = "mary.johnson@email.com",
                            FirstName = "Mary",
                            IsActive = true,
                            LastName = "Johnson",
                            PasswordHash = "$2a$11$w9r/nITfZDOgtLwm/nnyWeLZatS97IF6QWLZ9TlH5.NYytjw.B5iK",
                            Role = 2,
                            Username = "patient001"
                        });
                });

            modelBuilder.Entity("GrapheneTrace.Core.Models.Alert", b =>
                {
                    b.HasOne("GrapheneTrace.Core.Models.SensorFrame", "SensorFrame")
                        .WithMany("Alerts")
                        .HasForeignKey("FrameID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GrapheneTrace.Core.Models.Patient", "Patient")
                        .WithMany("Alerts")
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("SensorFrame");
                });

            modelBuilder.Entity("GrapheneTrace.Core.Models.ClinicalNote", b =>
                {
                    b.HasOne("GrapheneTrace.Core.Models.Clinician", "Clinician")
                        .WithMany("ClinicalNotes")
                        .HasForeignKey("ClinicianID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GrapheneTrace.Core.Models.SensorFrame", "SensorFrame")
                        .WithMany("ClinicalNotes")
                        .HasForeignKey("FrameID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GrapheneTrace.Core.Models.Patient", "Patient")
                        .WithMany("ClinicalNotes")
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinician");

                    b.Navigation("Patient");

                    b.Navigation("SensorFrame");
                });

            modelBuilder.Entity("GrapheneTrace.Core.Models.Clinician", b =>
                {
                    b.HasOne("GrapheneTrace.Core.Models.User", "User")
                        .WithOne("Clinician")
                        .HasForeignKey("GrapheneTrace.Core.Models.Clinician", "ClinicianID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GrapheneTrace.Core.Models.ClinicianPatient", b =>
                {
                    b.HasOne("GrapheneTrace.Core.Models.Clinician", "Clinician")
                        .WithMany("ClinicianPatients")
                        .HasForeignKey("ClinicianID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GrapheneTrace.Core.Models.Patient", "Patient")
                        .WithMany("ClinicianPatients")
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Clinician");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("GrapheneTrace.Core.Models.Comment", b =>
                {
                    b.HasOne("GrapheneTrace.Core.Models.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GrapheneTrace.Core.Models.SensorFrame", "SensorFrame")
                        .WithMany("Comments")
                        .HasForeignKey("FrameID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GrapheneTrace.Core.Models.Comment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GrapheneTrace.Core.Models.Patient", "Patient")
                        .WithMany("Comments")
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Author");

                    b.Navigation("ParentComment");

                    b.Navigation("Patient");

                    b.Navigation("SensorFrame");
                });

            modelBuilder.Entity("GrapheneTrace.Core.Models.FrameMetric", b =>
                {
                    b.HasOne("GrapheneTrace.Core.Models.SensorFrame", "SensorFrame")
                        .WithOne("FrameMetric")
                        .HasForeignKey("GrapheneTrace.Core.Models.FrameMetric", "FrameID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SensorFrame");
                });

            modelBuilder.Entity("GrapheneTrace.Core.Models.Patient", b =>
                {
                    b.HasOne("GrapheneTrace.Core.Models.User", "User")
                        .WithOne("Patient")
                        .HasForeignKey("GrapheneTrace.Core.Models.Patient", "PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GrapheneTrace.Core.Models.SensorFrame", b =>
                {
                    b.HasOne("GrapheneTrace.Core.Models.Patient", "Patient")
                        .WithMany("SensorFrames")
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("GrapheneTrace.Core.Models.Clinician", b =>
                {
                    b.Navigation("ClinicalNotes");

                    b.Navigation("ClinicianPatients");
                });

            modelBuilder.Entity("GrapheneTrace.Core.Models.Comment", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("GrapheneTrace.Core.Models.Patient", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("ClinicalNotes");

                    b.Navigation("ClinicianPatients");

                    b.Navigation("Comments");

                    b.Navigation("SensorFrames");
                });

            modelBuilder.Entity("GrapheneTrace.Core.Models.SensorFrame", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("ClinicalNotes");

                    b.Navigation("Comments");

                    b.Navigation("FrameMetric");
                });

            modelBuilder.Entity("GrapheneTrace.Core.Models.User", b =>
                {
                    b.Navigation("Clinician");

                    b.Navigation("Patient");
                });
#pragma warning restore 612, 618
        }
    }
}
